#!/bin/bash -u
##
# ------------------------------------------------------------------------
#     Copyright (C) 2012 Ericsson AB. All rights reserved.
# ------------------------------------------------------------------------
##
# Name:
#       mac
# Description:
#       The "get mac" sub-command of the shelfmngr tool.
##
# Changelog:
# Fri Mar 09 2012 - Francesco Rainone (efrarai)
#	First Version
##

. $SHELFMNGR_DIR/$LIB_COMMON_DIR/shelfmngr_common.sh
. $SHELFMNGR_DIR/$LIB_COMMON_DIR/snmp_queries.sh
check_debug


function is_verbose(){
	return $OPT_VERBOSE	
}

function get_mac(){
	GET_MAC
}

function usage(){
	cat $MAN_DIR/get_mac.man
}

function parse_cmdline(){
	# LONG_OPTIONS is a list of space-separated multi-character options.
	#  The string must be in the form:
	#   Example: 'option1 option2 ... optionN'.
	#  Options that takes an argument must be followed by a colon:
	#   Example: 'option1: option2 ... optionN:'
	#  Options with an optional argument must be followed by a double colon:
	#   Example: 'option1:: option2:: ... optionN'
	local LONG_OPTIONS='help verbose eth=: base'
	
	[ $# -le 0 ] && usage && abort 'missing parameter'
	
	/usr/bin/getopt --quiet --quiet-output --longoptions="$LONG_OPTIONS" -- "$@"
	EXIT_CODE=$?
	if [ $EXIT_CODE -ne $TRUE ]; then
		usage
		abort "Command line parameter error"
	fi	
	local ARGS="$@"
	eval set -- "$ARGS"
	
	# Make sure to handle the cases for all the options listed in OPTIONS
	#  and LONG_OPTIONS and to fill up the right script-wide variables.
	while [ $# -gt 0 ]; do		
		case "$1" in
			$(check_board_format $1 && echo $1))
				OPT_BOARD=$TRUE
				BOARD=$1				
			;;
			--eth=*)
				[ $OPT_BASE -eq $TRUE ] && abort 'only one of "--eth" and "--base" can be specified'				
				OPT_ETH=$TRUE				
				if [[ $1 =~ ^--eth=.+$ ]]; then
					OPT_ETH_ARG=$(echo $1 | tr [:upper:] [:lower:] | awk -F'=' '{print $2}')
				else
					abort 'missing mandatory parameter'
				fi				
				
				if [ $OPT_ETH_ARG != 'all' ]; then
					[[ $OPT_ETH_ARG =~ ^[0-9]$ ]] && OPT_ETH_ARG="eth$OPT_ETH_ARG"
					! check_eth $OPT_ETH_ARG && abort "the option \"$1\" is in the wrong format"				
				fi				
			;;
			--base)
				[ $OPT_ETH -eq $TRUE ] && abort 'only one of "--eth" and "--base" can be specified'
				OPT_BASE=$TRUE
			;;
			all-boards)
				[ $OPT_ALL_SLOTS -eq $TRUE ] && abort 'only one of "all-boards" and "all-slots" can be specified'
				OPT_ALL_BOARDS=$TRUE
			;;
			all-slots)
				[ $OPT_ALL_BOARDS -eq $TRUE ] && abort 'only one of "all-boards" and "all-slots" can be specified'
				OPT_ALL_SLOTS=$TRUE
			;;
			--help)
				usage
				exit $TRUE
			;;
			--verbose)				
				OPT_VERBOSE=$TRUE				
			;;			
			--)
				# "end of argument list"
				shift
				break
			;;
			*)
				abort "unrecognized option ($1)"
			;;
		esac
		shift
	done
	[[ $OPT_BOARD -eq $FALSE && $OPT_ALL_SLOTS -eq $FALSE && $OPT_ALL_BOARDS -eq $FALSE ]] && abort 'missing parameter'
	[[ $OPT_ETH -eq $FALSE && $OPT_BASE -eq $FALSE ]] && abort 'you must specify one option among --eth=<n> or --base'
}

OPT_VERBOSE=$FALSE
OPT_ETH=$FALSE
OPT_ETH_ARG=''
OPT_BASE=$FALSE
OPT_ALL=$FALSE
OPT_ALL_BOARDS=$FALSE
OPT_ALL_SLOTS=$FALSE
OPT_BOARD=$FALSE
BOARD=''
parse_cmdline $@
get_mac
exit $?