#!/bin/bash -u
##
# ------------------------------------------------------------------------
#     Copyright (C) 2012 Ericsson AB. All rights reserved.
# ------------------------------------------------------------------------
##
# Name:
#       master
# Description:
#       The "get master" sub-command of the shelfmngr tool.
##
# Changelog:
# Fri Mar 09 2012 - Francesco Rainone (efrarai)
#	First Version
##

. $SHELFMNGR_DIR/$LIB_COMMON_DIR/shelfmngr_common.sh
. $SHELFMNGR_DIR/$LIB_COMMON_DIR/snmp_queries.sh
check_debug


function is_verbose(){
	return $OPT_VERBOSE	
}

function get_master(){
	GET_MASTER
}

function usage(){
	cat $MAN_DIR/get_master.man
}

function parse_cmdline(){
	# LONG_OPTIONS is a list of space-separated multi-character options.
	#  The string must be in the form:
	#   Example: 'option1 option2 ... optionN'.
	#  Options that takes an argument must be followed by a colon:
	#   Example: 'option1: option2 ... optionN:'
	#  Options with an optional argument must be followed by a double colon:
	#   Example: 'option1:: option2:: ... optionN'
	local LONG_OPTIONS='help verbose'
	
	[ $# -le 0 ] && return $TRUE
	/usr/bin/getopt --quiet --quiet-output --longoptions="$LONG_OPTIONS" -- "$@"
	EXIT_CODE=$?
	if [ $EXIT_CODE -ne $TRUE ]; then
		usage
		abort "Command line parameter error"
	fi	
	local ARGS="$@"
	eval set -- "$ARGS"
	
	# Make sure to handle the cases for all the options listed in OPTIONS
	#  and LONG_OPTIONS and to fill up the right script-wide variables.
	while [ $# -gt 0 ]; do		
		case "$1" in
			--help)
				usage
				exit $TRUE
			;;
			--verbose)				
				OPT_VERBOSE=$TRUE				
			;;			
			--)
				# "end of argument list"
				shift
				break
			;;
			*)
				abort "unrecognized option ($1)"
			;;
		esac
		shift
	done
}

OPT_VERBOSE=$FALSE
parse_cmdline $@
get_master
exit $?