#!/bin/bash
##
# ------------------------------------------------------------------------
#     Copyright (C) 2013 Ericsson AB. All rights reserved.
# ------------------------------------------------------------------------
##
# Name:
#       eri-ipmitool
# Description:
#       A script to wrap the invocation of eri-ipmitool by TS user.
# Note:
#       None.
##
# Usage:
#       None.
##
# Output:
#       None.
##
# Changelog:
# - Thu Nov 08 2013  - Madhu Muthyala (xmadmut)
#       First version.
##

/usr/bin/sudo /usr/sbin/eri-ipmitool $@
exit $?

