#!/bin/bash
##
# ------------------------------------------------------------------------
#     Copyright (C) 2013 Ericsson AB. All rights reserved.
# ------------------------------------------------------------------------
##
# Name:
#       partls
# Description:
#       A script to wrap the invocation of fdisk with -l option by TS user.
# Note:
#       None.
##
# Usage:
#       None.
##
# Output:
#       None.
##
# Changelog:
# - Thu Nov 08 2013  - Madhu Muthyala (xmadmut)
#       First version.
##

function help()
{
	echo -e "\nUsage: partls\n"
}

if [ $# -gt 0 ] ; then
	echo -n "Incorrect usage"
	help
	exit 2
else 
	/usr/bin/sudo /sbin/fdisk -l
fi

exit $?


