#!/bin/bash
##
# ------------------------------------------------------------------------
#     Copyright (C) 2015 Ericsson AB. All rights reserved.
# ------------------------------------------------------------------------
##
# Name:
#       apos_ftp-config
# Description:
#       A script to maintain ftp mode information in vsftpd.conf file.
# Note:
#       This script is intended to be deployed to the
#       /usr/lib/lde/config-management/ directory.
#
#       It relies on the /opt/ap/apos/conf/apos_common.sh library.
##
# Changelog:
# - Wed Feb 11 2015 - Dharma Teja (Xdhatej)
##      First Version
# LDE_deployment:
#       type:           config
#       priority:       560
##

##
# libraries -------------------------------------------------------------- BEGIN
if [ -r /opt/ap/apos/conf/apos_common.sh ]; then
        . /opt/ap/apos/conf/apos_common.sh
else
        echo '/opt/ap/apos/conf/apos_common.sh not found or not readable!' >&2
        exit 1
fi
# libraries ---------------------------------------------------------------- END
##

# functions -------------------------------------------------------------- BEGIN
function usage(){
        cat << HEREDOC
Usage: $0 <action> <phase> [<etc_root>]
where:
        <action> can be "start" or "stop" or "config"
        <phase> can be "init" or "reload"
        <etc_root> (optional) specifies the base folder where the configuration
                   will be generated (/etc by default)
HEREDOC
}

function do_start(){
        # TO-DO: implement the start phase if needed.
        return
}

function do_stop(){
        # TO-DO: implement the stop phase if needed.
        return
}

function do_config(){
 	local FTP_STATE=0
        # fetch the FTP mode value
        if [ -f $FTPMODE_CONF_FILE ]; then
                FTP_STATE=$(cat $FTPMODE_CONF_FILE)
            [ ! -r $CONFIG_FILE_LIST ] && apos_abort "File \"$CONFIG_FILE_LIST\" not found!"
                 if [ "$FTP_STATE" -eq 0 ]; then
                    sed -i '/connect_from_port_20=YES/d' $CONFIG_FILE_LIST
                    [ $? -ne 0 ] && apos_abort "failure while modifying file $CONFIG_FILE_LIST"
                else
                    if ! grep -q 'connect_from_port_20=YES' $CONFIG_FILE_LIST; then
                        sed -i '/pasv_max_port=30100/a connect_from_port_20=YES' $CONFIG_FILE_LIST
                        [ $? -ne 0 ] && apos_abort "failure while modifying file $CONFIG_FILE_LIST"
                    fi
                fi

        else
            apos_log 'user.info' "Skipping configuration of $CONFIG_FILE_LIST ($FTPMODE_CONF_FILE file not present)"
        fi
}
# functions ---------------------------------------------------------------- END
##

##
# variables -------------------------------------------------------------- BEGIN
FTPMODE_CONF_FILE="/etc/apos_ftp_state.conf"

CONFIG_FILE_LIST='/opt/ap/apos/conf/vsftpd/vsftpd.conf'
# variables ---------------------------------------------------------------- END
##

##
# main ------------------------------------------------------------------- BEGIN
##
# LDE config scripts called with the following:
# param 1: action - start, stop or config
# param 2: generate phase - init or reload
# param 3: root path where config should be generated

apos_intro $0

if [ $# -lt 2 ]; then
        usage
        apos_abort 'missing parameter'
fi

if [ $(</etc/cluster/nodes/this/type) != 'control' ]; then
        apos_abort 'this script must be run ONLY in control nodes'
fi

ACTION="$1"
PHASE="$2"
case "$ACTION" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        config)
                do_config
                ;;
        *)
                usage
                ;;
esac

apos_outro
exit $TRUE
# main --------------------------------------------------------------------- END
##

                    
