#!/bin/bash -u
##
# ------------------------------------------------------------------------
#     Copyright (C) 2012 Ericsson AB. All rights reserved.
# ------------------------------------------------------------------------
##
# Name:
#       master
# Description:
#       The "set master" sub-command of the shelfmngr tool.
##
# Changelog:
# Fri Mar 09 2012 - Francesco Rainone (efrarai)
#	First Version
##

. $SHELFMNGR_DIR/$LIB_COMMON_DIR/shelfmngr_common.sh
. $SHELFMNGR_DIR/$LIB_COMMON_DIR/snmp_queries.sh
check_debug


function is_verbose(){
	return $OPT_VERBOSE	
}

function set_master(){
	SET_MASTER
}

function usage(){
	cat $MAN_DIR/set_master.man
}

function parse_cmdline(){
	# LONG_OPTIONS is a list of space-separated multi-character options.
	#  The string must be in the form:
	#   Example: 'option1 option2 ... optionN'.
	#  Options that takes an argument must be followed by a colon:
	#   Example: 'option1: option2 ... optionN:'
	#  Options with an optional argument must be followed by a double colon:
	#   Example: 'option1:: option2:: ... optionN'
	local LONG_OPTIONS='help verbose'
	
	[ $# -le 0 ] && usage && abort 'missing parameter'
	
	/usr/bin/getopt --quiet --quiet-output --longoptions="$LONG_OPTIONS" -- "$@"
	EXIT_CODE=$?
	if [ $EXIT_CODE -ne $TRUE ]; then
		usage
		abort "Command line parameter error"
	fi	
	local ARGS="$@"
	eval set -- "$ARGS"
	
	# Make sure to handle the cases for all the options listed in OPTIONS
	#  and LONG_OPTIONS and to fill up the right script-wide variables.
	while [ $# -gt 0 ]; do		
		case "$1" in
			$(check_board_format $1 && echo $1))
				[ $OPT_NONE -eq $TRUE ] && abort 'only one of <board> and "none" options can be specified'
				OPT_BOARD=$TRUE
				BOARD=$1
				if ! boards_are_equal $BOARD $SC_A; then
					if ! boards_are_equal $BOARD $SC_B; then
						abort "this applies only to \"$SC_A\" (slot $SC_A_SLOT) and \"$SC_B\" (slot $SC_B_SLOT) boards"
					fi
				fi
			;;
			none)
				[ $OPT_BOARD -eq $TRUE ] && abort 'only one of <board> and "none" options can be specified'
				OPT_NONE=$TRUE
			;;
			all-boards)
				abort "this applies only to \"$SC_A\" (slot $SC_A_SLOT) and \"$SC_B\" (slot $SC_B_SLOT) boards"
			;;
			all-slots)
				abort "this applies only to \"$SC_A\" (slot $SC_A_SLOT) and \"$SC_B\" (slot $SC_B_SLOT) boards"
			;;
			--help)
				usage
				exit $TRUE
			;;
			--verbose)				
				OPT_VERBOSE=$TRUE				
			;;			
			--)
				# "end of argument list"
				shift
				break
			;;
			*)
				abort "unrecognized option ($1)"
			;;
		esac
		shift
	done
	[[ $OPT_BOARD -ne $TRUE && $OPT_NONE -ne $TRUE ]] && abort 'missing parameter'
}

OPT_VERBOSE=$FALSE
SC_A='sc_a'
SC_A_SLOT=$(get_slot_by_name $SC_A)
SC_B='sc_b'
SC_B_SLOT=$(get_slot_by_name $SC_B)
OPT_BOARD=$FALSE
BOARD=''
OPT_NONE=$FALSE
parse_cmdline $@
set_master
exit $?